version: "3.9"

services:
  dev:
    build: .
    ports:
      - "4000:4000"
    env_file: ./config/dev.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
  prod:
    build: .
    ports:
      - "4000:5000"
    env_file: ./config/prod.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
